### ISSUE TITLE
java.util.ArrayList cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by The-Don-Himself** [PommeVerte/gremlin-php#42]
I regularly rebuild from JanusGraph master on my development machine. I also recently updated gremlin-php to latest 3.0.2

As of 2 days ago, I've been getting this error when trying to send certain queries.

````
A general server error occurred that prevented the request from being processed.
 : java.util.ArrayList cannot be cast to java.lang.String

 ===================  SERVER TRACE  =========================
array (
  'stackTrace' => 'java.lang.ClassCastException: java.util.ArrayList cannot be c
ast to java.lang.String
        at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor.evalOp
Internal(AbstractEvalOpProcessor.java:236)
        at org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor.eva
lOp(SessionOpProcessor.java:191)
        at org.apache.tinkerpop.gremlin.server.handler.OpExecutorHandler.channel
Read0(OpExecutorHandler.java:68)
        at org.apache.tinkerpop.gremlin.server.handler.OpExecutorHandler.channel
Read0(OpExecutorHandler.java:43)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChanne
lInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:346)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:346)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:346)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:346)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:346)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:346)
        at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler
$1.channelRead(WebSocketServerProtocolHandler.java:147)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMes
sageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:346)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1069)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:346)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Defau
ltChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:353)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:652)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:575)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:489)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:140)
        at java.lang.Thread.run(Unknown Source)
',
  'exceptions' =>
  array (
    0 => 'java.lang.ClassCastException',
  ),
)
 ============================================================
````

The sample query I'm trying to send is

````
g.addV(label, 'users', 'users_id', 2244994945, 'name', 'TwitterDev', 'screen_name', 'TwitterDev', 'description', 'Developer and Platform Relations @Twitter. We are developer advocates. We can\'t answer all your questions, but we listen to all of them!', 'followers_count', 429831, 'created_at', 1386995755000, 'verified', true, 'lang', 'en')"
````

Submitting this query directly in gremlin works but via the gremlin-php lib does not. Any ideas why?

**Comment by The-Don-Himself** [comment]
FYI, this is my schema, so it's not the issue:

````
mgmt = graph.openManagement()
text = mgmt.makePropertyKey('text').dataType(String.class).cardinality(Cardinality.SINGLE).make()
retweet_count = mgmt.makePropertyKey('retweet_count').dataType(Integer.class).cardinality(Cardinality.SINGLE).make()
retweeted = mgmt.makePropertyKey('retweeted').dataType(Boolean.class).cardinality(Cardinality.SINGLE).make()
created_at = mgmt.makePropertyKey('created_at').dataType(Date.class).cardinality(Cardinality.SINGLE).make()
source = mgmt.makePropertyKey('source').dataType(String.class).cardinality(Cardinality.SINGLE).make()
tweets_id = mgmt.makePropertyKey('tweets_id').dataType(Long.class).cardinality(Cardinality.SINGLE).make()
name = mgmt.makePropertyKey('name').dataType(String.class).cardinality(Cardinality.SINGLE).make()
php bin/console graph:schema:create
screen_name = mgmt.makePropertyKey('screen_name').dataType(String.class).cardinality(Cardinality.SINGLE).make()
description = mgmt.makePropertyKey('description').dataType(String.class).cardinality(Cardinality.SINGLE).make()
followers_count = mgmt.makePropertyKey('followers_count').dataType(Integer.class).cardinality(Cardinality.SINGLE).make()
verified = mgmt.makePropertyKey('verified').dataType(Boolean.class).cardinality(Cardinality.SINGLE).make()
lang = mgmt.makePropertyKey('lang').dataType(String.class).cardinality(Cardinality.SINGLE).make()
users_id = mgmt.makePropertyKey('users_id').dataType(Long.class).cardinality(Cardinality.SINGLE).make()
tweets = mgmt.makeVertexLabel('tweets').make()
users = mgmt.makeVertexLabel('users').make()
follows = mgmt.makeEdgeLabel('follows').multiplicity(MULTI).make()
likes = mgmt.makeEdgeLabel('likes').multiplicity(MULTI).make()
retweets = mgmt.makeEdgeLabel('retweets').multiplicity(MULTI).make()
tweeted = mgmt.makeEdgeLabel('tweeted').multiplicity(ONE2MANY).make()
mgmt.buildIndex('byTweetsIdComposite', Vertex.class).addKey(tweets_id).unique().indexOnly(tweets).buildCompositeIndex()
mgmt.buildIndex('tweetsMixed', Vertex.class).addKey(tweets_id).addKey(text, Mapping.TEXT.asParameter()).addKey(retweet_count).addKey(created_at).addKey(retweeted).addKey(source, Mapping.STRING.asParameter()).indexOnly(tweets).buildMixedIndex("search")
mgmt.buildIndex('byUsersIdComposite', Vertex.class).addKey(users_id).unique().indexOnly(users).buildCompositeIndex()
mgmt.buildIndex('byScreenNameComposite', Vertex.class).addKey(screen_name).unique().indexOnly(users).buildCompositeIndex()
mgmt.buildIndex('usersMixed', Vertex.class).addKey(users_id).addKey(name, Mapping.TEXTSTRING.asParameter()).addKey(screen_name, Mapping.STRING.asParameter()).addKey(description, Mapping.TEXT.asParameter()).addKey(followers_count).addKey(created_at).addKey(verified).addKey(lang, Mapping.STRING.asParameter()).indexOnly(users).buildMixedIndex("search")
mgmt.commit()
````

**Comment by PommeVerte** [comment]
Hi. Do you happen to know which version of gremlin-server is being used here? (on the JanusGraph master)

**Comment by PommeVerte** [comment]
Hmmm I'll need to recreate an env where I can rebuild these projects to give this a shot myself. Can you include a full php example that fails? (we should start testing this without a schema for one)

**Comment by The-Don-Himself** [comment]
@PommeVerte sorry for the delay in getting back.

Strangely, I'm not quite sure how to get the gremlin-server version. On windows, 
````
C:\janusgraph>bin\gremlin.bat -v
````
gives 
````
JanusGraph 0.2.0-SNAPSHOT, Apache TinkerPop 3.2.6
````
while
````
C:\janusgraph>bin\gremlin-server.bat -v
````
throws an error


The data I tried to persist in JanusGraph comes straight from the Twitter API sample response for /users/show -> link -> https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-show

So this is the gremlin command I want to execute: 

g.addV(label, 'users', 'users_id', 2960784075, 'name', 'Jesus Rafael Abreu M', 'screen_name', 'chuomaraver', 'description', '', 'followers_count', 1, 'created_at', 1420401486000, 'verified', false, 'lang', 'es')

So basically this command fails,

````
        $db->open();
        $db->transactionStart();
        $db->send("g.addV(label, 'users', 'users_id', 2960784075, 'name', 'Jesus Rafael Abreu M', 'screen_name', 'chuomaraver', 'description', '', 'followers_count', 1, 'created_at', 1420401486000, 'verified', false, 'lang', 'es')");
        $db->transactionStop(true);
        $db->close();
````

But this one succeeds

````
gremlin> g.addV(label, 'users', 'users_id', 2960784075, 'name', 'Jesus Rafael Abreu M', 'screen_name', 'chuomaraver', 'description', '', 'followers_count', 1, 'created_at', 1420401486000, 'verified', false, 'lang', 'es')
````

Perhaps you can try send that query via gremlin-php on JanusGraph master build, just rebuilt again a few minutes ago but the error persists. It's worth noting that other commands like g.V().count() execute successfully. Even commands to create the schema succeed, but this on fails. Also tried without a schema  and it fails although I don't think it matters because the command executes successfully with a schema when typed direct in gremlin console.

**Comment by The-Don-Himself** [comment]
Rookie mistake with a bit of a hard to debug situation. I'm try to create a sort of Object to Graph Mapper for PHP based on this library not yet complete but have an alpha, [gremlin-orm](https://github.com/the-don-himself/gremlin-ogm).

The problem is that I was sending an array but since I'm using Symfony Console, outputting an array of single element shows you a string single, so I thought I was still sending a string, var_dump exposes the issue. i.e

''''
$output->writeln($command);
string(211) "g.addV(label, 'users', 'users_id', 2960784075, 'name', 'Jesus Rafae
l Abreu M', 'screen_name', 'chuomaraver', 'description', '', 'followers_count',
1, 'created_at', 1420401486000, 'verified', false, 'lang', 'es')"
````
but 
````
var_dump($command);
array(1) {
  [0]=>
  string(211) "g.addV(label, 'users', 'users_id', 2960784075, 'name', 'Jesus Raf
ael Abreu M', 'screen_name', 'chuomaraver', 'description', '', 'followers_count'
, 1, 'created_at', 1420401486000, 'verified', false, 'lang', 'es')"
}
````
